---
apiVersion: v1
kind: Service
metadata:
  name: node-app-one-service
spec:
  type: LoadBalancer
  selector:
    app: node-app-one-deployment
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
