---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-one-deployment
  labels:
    app: node-app-one-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-one-deployment
  template:
    metadata:
      labels:
        app: node-app-one-deployment
    spec:
      containers:
      - name: node-app-one
        image: naresh240/nodeappone:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api1
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /api1
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
