---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-two-deployment
  labels:
    app: node-app-two-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-two-deployment
  template:
    metadata:
      labels:
        app: node-app-two-deployment
    spec:
      containers:
      - name: node-app-two
        image: naresh240/nodeapptwo:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /api2
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /api2
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
