---
apiVersion: v1
kind: Service
metadata:
  name: node-app-two-service
spec:
  type: LoadBalancer
  selector:
    app: node-app-two-deployment
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
